# Generated by Django 5.0.6 on 2024-06-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegram", "0002_userbusness_hotel_invitation_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="amenities",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="booking",
            name="number_of_people",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
