# Generated by Django 5.0.6 on 2024-06-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegram", "0003_booking_amenities_booking_number_of_people"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="distance_to_beach",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="booking",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
