# Generated by Django 5.0.6 on 2024-06-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegram", "0004_booking_distance_to_beach_booking_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="price",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
