# Generated by Django 5.0.6 on 2024-06-04 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegram", "0005_booking_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="user_id",
            new_name="region",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="accommodation_type",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="pension",
        ),
        migrations.AddField(
            model_name="booking",
            name="photos",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="booking",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
